import { useEffect, useState } from 'react';
import { Check, Loader2, Plus, Sparkles, X } from 'lucide-react';
import {
  applyGraphProposal,
  getPendingGraphProposal,
  rejectGraphProposal,
  startEventOperatorRun,
  type EventGraphProposal,
  type GraphOperation,
} from '../api/client';

type Language = 'zh' | 'en';
const COPY: Record<Language, { title: string; start: string; starting: string; empty: string; template: string; reason: string; entity: string; apply: string; applying: string; reject: string; rejecting: string; doneLabel: string; close: string; none: string; error: string }> = {
  zh: {
    title: 'AI 推进',
    start: '开始 AI 拆解',
    starting: '正在拆解…',
    empty: '还没有待审阅的建议。点「开始 AI 拆解」，让 AI 基于这个事件生成下一步。',
    template: '模板模式 · 尚未接入真实模型，建议由本地模板基于已有内容生成',
    reason: '理由',
    entity: '实体',
    apply: '接受并生成',
    applying: '正在生成…',
    reject: '拒绝',
    rejecting: '拒绝中…',
    doneLabel: '已生成',
    close: '关闭',
    none: '没有可接受的建议',
    error: '操作失败',
  },
  en: {
    title: 'AI Push forward',
    start: 'Start AI breakdown',
    starting: 'Breaking down…',
    empty: 'No pending suggestions. Start an AI breakdown to derive next steps from this event.',
    template: 'Template mode · no real model connected — suggestions are generated by a local template from existing content',
    reason: 'Why',
    entity: 'Entity',
    apply: 'Accept & generate',
    applying: 'Generating…',
    reject: 'Reject',
    rejecting: 'Rejecting…',
    doneLabel: 'Generated',
    close: 'Close',
    none: 'Nothing to accept',
    error: 'Action failed',
  },
};

interface Props {
  language: Language;
  eventId: string;
  mindmapId: string;
  onNotice?: (message: string, type?: 'success' | 'info' | 'error') => void;
  onApplied: () => void;
  onClose: () => void;
}

export function AgentRunPanel({ language, eventId, mindmapId, onNotice, onApplied, onClose }: Props) {
  const t = COPY[language];
  const [proposal, setProposal] = useState<EventGraphProposal | null>(null);
  const [selection, setSelection] = useState<Set<string>>(new Set());
  const [loading, setLoading] = useState(false);
  const [started, setStarted] = useState(false);

  async function refresh() {
    const r = await getPendingGraphProposal(eventId);
    setProposal(r.proposal);
    if (r.proposal) setSelection(new Set(r.proposal.operations.map((o) => o.changeId)));
  }

  useEffect(() => {
    void refresh().catch(() => {});
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [eventId]);

  async function start() {
    setLoading(true);
    setStarted(true);
    try {
      const r = await startEventOperatorRun(eventId, { mindmapId, templateMaxOps: 6 });
      if (r.proposal) {
        setProposal(r.proposal);
        setSelection(new Set(r.proposal.operations.map((o) => o.changeId)));
        onNotice?.(language === 'zh' ? 'AI 已生成建议，请审阅。' : 'AI suggestions ready — review them.', 'info');
      } else {
        onNotice?.(language === 'zh' ? '没有可拆解的内容。' : 'Nothing to break down.', 'info');
      }
    } catch (err) {
      onNotice?.(err instanceof Error ? err.message : t.error, 'error');
    } finally {
      setLoading(false);
    }
  }

  async function apply() {
    if (!proposal) return;
    setLoading(true);
    try {
      const kept = proposal.operations.filter((o) => selection.has(o.changeId)).map((o) => o.changeId);
      const r = await applyGraphProposal(eventId, proposal.id, { selection: kept });
      onApplyResult(r);
    } catch (err) {
      onNotice?.(err instanceof Error ? err.message : t.error, 'error');
    } finally {
      setLoading(false);
    }
  }

  function onApplyResult(r: { proposal: EventGraphProposal; createdCommitments: number; appliedChanges: string[]; staleChangeIds: string[] }) {
    if (r.staleChangeIds.length > 0) {
      onNotice?.(language === 'zh' ? '事件已变化，建议已过期，请重新生成。' : 'The event changed — suggestions are stale, regenerate.', 'error');
      return;
    }
    const msg = language === 'zh'
      ? `已生成 ${r.createdCommitments} 个承诺，并更新了画布。`
      : `Generated ${r.createdCommitments} commitments and updated the canvas.`;
    onNotice?.(msg, 'success');
    setProposal(null);
    onApplied();
    onClose();
  }

  async function reject() {
    if (!proposal) return;
    setLoading(true);
    try {
      await rejectGraphProposal(eventId, proposal.id);
      onNotice?.(language === 'zh' ? '已拒绝。' : 'Rejected.', 'info');
      setProposal(null);
      onApplied();
    } catch (err) {
      onNotice?.(err instanceof Error ? err.message : t.error, 'error');
    } finally {
      setLoading(false);
    }
  }

  function toggle(id: string) {
    setSelection((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={onClose} data-testid="agent-run-panel">
      <div className="flex max-h-[80vh] w-full max-w-2xl flex-col overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-2xl dark:border-gray-700 dark:bg-[#161b1a]" onClick={(e) => e.stopPropagation()}>
        <header className="flex items-center justify-between border-b border-gray-100 px-5 py-4 dark:border-gray-800">
          <div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-[#23877B]" /><h2 className="text-sm font-semibold text-gray-900 dark:text-gray-50">{t.title}</h2></div>
          <div className="flex items-center gap-3">
            <span className="rounded-full bg-[#23877B]/10 px-2 py-0.5 text-[10px] font-medium text-[#23877B]">{t.template}</span>
            <button onClick={onClose} aria-label={t.close} className="rounded-lg p-1.5 text-gray-500 hover:bg-gray-100 dark:hover:bg-gray-800"><X className="h-4 w-4" /></button>
          </div>
        </header>

        <div className="flex-1 overflow-y-auto px-5 py-4">
          {!proposal && (
            <div className="flex flex-col items-center gap-4 py-10 text-center">
              <p className="max-w-sm text-sm text-gray-500 dark:text-gray-400">{t.empty}</p>
              <button
                onClick={() => void start()}
                disabled={loading}
                data-testid="agent-run-start"
                className="flex items-center gap-2 rounded-lg bg-[#23877B] px-4 py-2.5 text-sm font-medium text-white shadow-sm hover:opacity-90 disabled:opacity-60"
              >
                {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}
                {started && loading ? t.starting : t.start}
              </button>
            </div>
          )}

          {proposal && (
            <>
              <p className="mb-3 text-sm text-gray-600 dark:text-gray-300">{proposal.summary}</p>
              <div className="space-y-2">
                {proposal.operations.map((op) => <SuggestionCard key={op.changeId} op={op} checked={selection.has(op.changeId)} onToggle={() => toggle(op.changeId)} language={language} />)}
              </div>
              {proposal.operations.filter((o) => selection.has(o.changeId)).length === 0 && <p className="mt-3 text-xs text-gray-400">{t.none}</p>}
            </>
          )}
        </div>

        {proposal && (
          <footer className="flex items-center justify-end gap-2 border-t border-gray-100 px-5 py-4 dark:border-gray-800">
            <button onClick={() => void reject()} disabled={loading} className="rounded-lg px-3.5 py-2 text-sm text-gray-600 hover:bg-gray-100 disabled:opacity-50 dark:text-gray-300 dark:hover:bg-gray-800" data-testid="agent-run-reject">
              {loading ? t.rejecting : t.reject}
            </button>
            <button onClick={() => void apply()} disabled={loading || selection.size === 0} className="flex items-center gap-2 rounded-lg bg-[#23877B] px-4 py-2.5 text-sm font-medium text-white shadow-sm hover:opacity-90 disabled:opacity-50" data-testid="agent-run-apply">
              {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />}
              {loading ? t.applying : `${t.apply}（${selection.size}）`}
            </button>
          </footer>
        )}
      </div>
    </div>
  );
}

function SuggestionCard({ op, checked, onToggle, language }: { op: GraphOperation; checked: boolean; onToggle: () => void; language: Language }) {
  const kind = op.node?.kind ?? op.op;
  const entity = op.domainDraft?.entity;
  const kindPill: Record<string, string> = {
    task: language === 'zh' ? '任务' : 'Task',
    waiting: language === 'zh' ? '等待' : 'Waiting',
    decision: language === 'zh' ? '决策' : 'Decision',
    branch: language === 'zh' ? '分支' : 'Branch',
    add_node: language === 'zh' ? '新增节点' : 'Add node',
    update_node: language === 'zh' ? '更新节点' : 'Update',
    move_node: language === 'zh' ? '移动节点' : 'Move',
  };
  const entityPill = entity && entity !== 'none' ? (language === 'zh' ? { commitment: '承诺', waiting_commitment: '等待承诺', decision: '决策', outcome: '结果' }[entity] ?? entity : entity) : null;
  const text = op.node?.text ?? op.reason;
  return (
    <div className={`flex items-start gap-3 rounded-xl border p-3 transition ${checked ? 'border-[#23877B]/50 bg-[#23877B]/[0.04]' : 'border-gray-200 bg-white opacity-60 dark:border-gray-700 dark:bg-gray-900'}`}>
      <input type="checkbox" checked={checked} onChange={onToggle} aria-label="select suggestion" className="mt-0.5 h-4 w-4 accent-[#23877B]" data-testid={`agent-suggestion-${op.changeId}`} />
      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-2">
          <span className="text-sm font-medium text-gray-900 dark:text-gray-100">{text}</span>
          <span className="rounded bg-gray-100 px-1.5 py-0.5 text-[10px] text-gray-500 dark:bg-gray-800 dark:text-gray-400">{kindPill[kind] ?? kind}</span>
          {entityPill && <span className="rounded bg-[#23877B]/10 px-1.5 py-0.5 text-[10px] text-[#23877B]">{entityPill}</span>}
        </div>
        <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">{op.reason}</p>
        <p className="mt-1 text-[10px] tabular-nums text-gray-400">{Math.round(op.confidence * 100)}%</p>
      </div>
    </div>
  );
}