/**
 * Mind map storage.
 *
 * Persistence: one JSON file per map under
 * `<workspaceRoot>/.dailyflow/mindmaps/<id>.json`.
 *
 * We deliberately do NOT piggy-back on the v2 markdown repository:
 *  - mind maps are inherently graph data, not markdown;
 *  - the v2 repository is append-audit / conflict-resolved; we just need
 *    a single-document save with no concurrent writers in the UI today.
 *
 * Concurrency: the in-process write queue (`saveQueue`) serializes writes
 * per file. Two near-simultaneous saves can't interleave a half-written
 * JSON, but we do NOT add file-level locks for now because the UI is the
 * sole writer.
 *
 * Schema versioning (SPEC §2.2):
 *   - `version: 1` — pre-Topic-Space format. Read tolerantly, no rewrite.
 *   - `version: 2` — current. Adds `spaceId` and per-node `kind` / `tag`
 *     / `taskId`. Any PUT auto-bumps to v2. New creates write v2.
 */
import { promises as fs } from 'fs';
import path from 'path';
import { ulid } from 'ulid';
import { loadConfig } from './config.js';
import type { MindMap, MindMapInput, MindMapNode, MindMapEdge, MindMapNodeKind } from '../types/mindmap.js';
import { DEFAULT_MINDMAP_NODE_KIND } from '../types/mindmap.js';

/** Current schema version for new writes. Reads accept both 1 and 2. */
const SCHEMA_VERSION = 2 as const;

/** Maps older than this are still readable. */
const MIN_SUPPORTED_VERSION = 1 as const;

function getDir(): string {
  // loadConfig is async; we expose `getDir` only after the config resolves.
  // See `withDir` below.
  throw new Error('getDir called without workspaceRoot; use withDir');
}

async function withDir<T>(fn: (dir: string) => Promise<T>): Promise<T> {
  const config = await loadConfig();
  const dir = path.join(config.workspaceRoot, '.dailyflow', 'mindmaps');
  await fs.mkdir(dir, { recursive: true });
  return fn(dir);
}

function fileFor(dir: string, id: string): string {
  // id is generated by `ulid()` and is url-safe; no sanitisation needed.
  return path.join(dir, `${id}.json`);
}

const saveQueue = new Map<string, Promise<unknown>>();

async function readMapFile(filePath: string): Promise<MindMap> {
  const raw = await fs.readFile(filePath, 'utf-8');
  return JSON.parse(raw) as MindMap;
}

async function writeMapFile(filePath: string, map: MindMap): Promise<void> {
  // Serialize per file so concurrent updates don't interleave a half-written
  // document on disk.
  const previous = saveQueue.get(filePath) ?? Promise.resolve();
  const next = previous.then(() => fs.writeFile(filePath, JSON.stringify(map, null, 2), 'utf-8'));
  saveQueue.set(filePath, next.catch(() => undefined));
  await next;
}

/**
 * Fill default `kind` for any node that doesn't have one (SPEC §2.2:
 * "缺省 `kind === 'branch'` (兼容老节点)"). This is a pure function so
 * tests can pin its behavior.
 */
export function defaultNodeKind(node: MindMapNode): MindMapNode {
  if (node.kind) return node;
  return { ...node, kind: DEFAULT_MINDMAP_NODE_KIND };
}

/** Apply `defaultNodeKind` to every node in an array. */
function defaultNodeKinds(nodes: MindMapNode[]): MindMapNode[] {
  return nodes.map(defaultNodeKind);
}

function emptyMap(title: string, now: string, spaceId?: string): MindMap {
  const id = ulid();
  const rootId = ulid();
  const root: MindMapNode = {
    id: rootId,
    text: title || '中心主题',
    position: { x: 0, y: 0 },
    kind: 'root',
  };
  return {
    id,
    title: title || '未命名导图',
    rootId,
    nodes: [root],
    edges: [],
    version: SCHEMA_VERSION,
    ...(spaceId ? { spaceId } : {}),
    createdAt: now,
    updatedAt: now,
  };
}

export async function listMindMaps(): Promise<MindMap[]> {
  return withDir(async (dir) => {
    const entries = await fs.readdir(dir);
    const maps: MindMap[] = [];
    for (const entry of entries) {
      if (!entry.endsWith('.json')) continue;
      try {
        const map = await readMapFile(path.join(dir, entry));
        // Accept any supported version; unknown future versions are skipped
        // so a forward-incompatible change doesn't break the whole list.
        if (map && map.version >= MIN_SUPPORTED_VERSION && map.version <= SCHEMA_VERSION) {
          maps.push(map);
        }
      } catch (err) {
        // A corrupt file should not break the whole list. Log and skip.
        console.error(`[mindmaps] skip unreadable ${entry}:`, err);
      }
    }
    // Newest first by updatedAt.
    maps.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
    return maps;
  });
}

export async function getMindMap(id: string): Promise<MindMap | null> {
  return withDir(async (dir) => {
    const filePath = fileFor(dir, id);
    try {
      return await readMapFile(filePath);
    } catch (err: any) {
      if (err && err.code === 'ENOENT') return null;
      throw err;
    }
  });
}

export async function createMindMap(input: Partial<MindMapInput> = {}): Promise<MindMap> {
  const now = new Date().toISOString();
  const title = (input.title ?? '').trim() || '未命名导图';
  const map = emptyMap(title, now, input.spaceId);
  if (input.rootId) map.rootId = input.rootId;
  if (Array.isArray(input.nodes) && input.nodes.length > 0) {
    map.nodes = defaultNodeKinds(input.nodes);
    if (!map.nodes.find((n) => n.id === map.rootId) && map.nodes[0]) {
      map.rootId = map.nodes[0].id;
    }
  }
  if (Array.isArray(input.edges)) map.edges = input.edges;
  return withDir(async (dir) => {
    await writeMapFile(fileFor(dir, map.id), map);
    return map;
  });
}

export interface MindMapUpdate {
  title?: string;
  rootId?: string;
  nodes?: MindMapNode[];
  edges?: MindMapEdge[];
  /**
   * v2: allow the route (or TopicSpace) to set the reverse link. If
   * omitted, the existing `spaceId` is preserved.
   */
  spaceId?: string | null;
}

export async function updateMindMap(id: string, patch: MindMapUpdate): Promise<MindMap | null> {
  const now = new Date().toISOString();
  return withDir(async (dir) => {
    const filePath = fileFor(dir, id);
    let existing: MindMap;
    try {
      existing = await readMapFile(filePath);
    } catch (err: any) {
      if (err && err.code === 'ENOENT') return null;
      throw err;
    }
    // Any PUT auto-bumps to the current schema version (SPEC §3.3).
    // The resulting `nodes` array gets `kind: 'branch'` defaulted on
    // any node missing one — including nodes we inherited from the
    // v1 file on disk, not just the ones the client sent. This is
    // what makes the file truly forward-migrated to v2 shape.
    const baseNodes = patch.nodes !== undefined ? patch.nodes : existing.nodes;
    const next: MindMap = {
      ...existing,
      title: patch.title !== undefined ? patch.title : existing.title,
      rootId: patch.rootId !== undefined ? patch.rootId : existing.rootId,
      nodes: defaultNodeKinds(baseNodes),
      edges: patch.edges !== undefined ? patch.edges : existing.edges,
      version: SCHEMA_VERSION,
      updatedAt: now,
    };
    if (patch.spaceId !== undefined) {
      if (patch.spaceId === null) {
        delete next.spaceId;
      } else {
        next.spaceId = patch.spaceId;
      }
    } else if (existing.spaceId) {
      // Preserve existing reverse link.
      next.spaceId = existing.spaceId;
    }
    await writeMapFile(filePath, next);
    return next;
  });
}

export async function deleteMindMap(id: string): Promise<boolean> {
  return withDir(async (dir) => {
    const filePath = fileFor(dir, id);
    try {
      await fs.unlink(filePath);
      return true;
    } catch (err: any) {
      if (err && err.code === 'ENOENT') return false;
      throw err;
    }
  });
}

/**
 * Re-export the kind constant for callers that don't want a second import.
 */
export type { MindMapNodeKind };
