/**
 * Mind map storage.
 *
 * Persistence: one JSON file per map under
 * `<workspaceRoot>/.dailyflow/mindmaps/<id>.json`.
 *
 * We deliberately do NOT piggy-back on the v2 markdown repository:
 *  - mind maps are inherently graph data, not markdown;
 *  - the v2 repository is append-audit / conflict-resolved; we just need
 *    a single-document save with no concurrent writers in the UI today.
 *
 * Concurrency: the in-process write queue (`saveQueue`) serializes writes
 * per file. Two near-simultaneous saves can't interleave a half-written
 * JSON, but we do NOT add file-level locks for now because the UI is the
 * sole writer.
 */
import { promises as fs } from 'fs';
import path from 'path';
import { ulid } from 'ulid';
import { loadConfig } from './config.js';
import type { MindMap, MindMapInput, MindMapNode, MindMapEdge } from '../types/mindmap.js';

const SCHEMA_VERSION = 1 as const;

function getDir(): string {
  // loadConfig is async; we expose `getDir` only after the config resolves.
  // See `withDir` below.
  throw new Error('getDir called without workspaceRoot; use withDir');
}

async function withDir<T>(fn: (dir: string) => Promise<T>): Promise<T> {
  const config = await loadConfig();
  const dir = path.join(config.workspaceRoot, '.dailyflow', 'mindmaps');
  await fs.mkdir(dir, { recursive: true });
  return fn(dir);
}

function fileFor(dir: string, id: string): string {
  // id is generated by `ulid()` and is url-safe; no sanitisation needed.
  return path.join(dir, `${id}.json`);
}

const saveQueue = new Map<string, Promise<unknown>>();

async function readMapFile(filePath: string): Promise<MindMap> {
  const raw = await fs.readFile(filePath, 'utf-8');
  return JSON.parse(raw) as MindMap;
}

async function writeMapFile(filePath: string, map: MindMap): Promise<void> {
  // Serialize per file so concurrent updates don't interleave a half-written
  // document on disk.
  const previous = saveQueue.get(filePath) ?? Promise.resolve();
  const next = previous.then(() => fs.writeFile(filePath, JSON.stringify(map, null, 2), 'utf-8'));
  saveQueue.set(filePath, next.catch(() => undefined));
  await next;
}

function emptyMap(title: string, now: string): MindMap {
  const id = ulid();
  const rootId = ulid();
  const root: MindMapNode = { id: rootId, text: title || '中心主题', position: { x: 0, y: 0 } };
  return {
    id,
    title: title || '未命名导图',
    rootId,
    nodes: [root],
    edges: [],
    version: SCHEMA_VERSION,
    createdAt: now,
    updatedAt: now,
  };
}

export async function listMindMaps(): Promise<MindMap[]> {
  return withDir(async (dir) => {
    const entries = await fs.readdir(dir);
    const maps: MindMap[] = [];
    for (const entry of entries) {
      if (!entry.endsWith('.json')) continue;
      try {
        const map = await readMapFile(path.join(dir, entry));
        if (map && map.version === SCHEMA_VERSION) {
          maps.push(map);
        }
      } catch (err) {
        // A corrupt file should not break the whole list. Log and skip.
        console.error(`[mindmaps] skip unreadable ${entry}:`, err);
      }
    }
    // Newest first by updatedAt.
    maps.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
    return maps;
  });
}

export async function getMindMap(id: string): Promise<MindMap | null> {
  return withDir(async (dir) => {
    const filePath = fileFor(dir, id);
    try {
      return await readMapFile(filePath);
    } catch (err: any) {
      if (err && err.code === 'ENOENT') return null;
      throw err;
    }
  });
}

export async function createMindMap(input: Partial<MindMapInput> = {}): Promise<MindMap> {
  const now = new Date().toISOString();
  const title = (input.title ?? '').trim() || '未命名导图';
  const map = emptyMap(title, now);
  if (input.rootId) map.rootId = input.rootId;
  if (Array.isArray(input.nodes) && input.nodes.length > 0) {
    map.nodes = input.nodes;
    if (!map.nodes.find((n) => n.id === map.rootId) && map.nodes[0]) {
      map.rootId = map.nodes[0].id;
    }
  }
  if (Array.isArray(input.edges)) map.edges = input.edges;
  return withDir(async (dir) => {
    await writeMapFile(fileFor(dir, map.id), map);
    return map;
  });
}

export interface MindMapUpdate {
  title?: string;
  rootId?: string;
  nodes?: MindMapNode[];
  edges?: MindMapEdge[];
}

export async function updateMindMap(id: string, patch: MindMapUpdate): Promise<MindMap | null> {
  const now = new Date().toISOString();
  return withDir(async (dir) => {
    const filePath = fileFor(dir, id);
    let existing: MindMap;
    try {
      existing = await readMapFile(filePath);
    } catch (err: any) {
      if (err && err.code === 'ENOENT') return null;
      throw err;
    }
    const next: MindMap = {
      ...existing,
      title: patch.title !== undefined ? patch.title : existing.title,
      rootId: patch.rootId !== undefined ? patch.rootId : existing.rootId,
      nodes: patch.nodes !== undefined ? patch.nodes : existing.nodes,
      edges: patch.edges !== undefined ? patch.edges : existing.edges,
      version: SCHEMA_VERSION,
      updatedAt: now,
    };
    await writeMapFile(filePath, next);
    return next;
  });
}

export async function deleteMindMap(id: string): Promise<boolean> {
  return withDir(async (dir) => {
    const filePath = fileFor(dir, id);
    try {
      await fs.unlink(filePath);
      return true;
    } catch (err: any) {
      if (err && err.code === 'ENOENT') return false;
      throw err;
    }
  });
}
