/**
 * Mind map storage.
 *
 * Persistence: one JSON file per map under
 * `<workspaceRoot>/.dailyflow/mindmaps/<id>.json`.
 *
 * We deliberately do NOT piggy-back on the v2 markdown repository:
 *  - mind maps are inherently graph data, not markdown;
 *  - the v2 repository is append-audit / conflict-resolved; we just need
 *    a single-document save with no concurrent writers in the UI today.
 *
 * Concurrency: the in-process mutation queue serializes the complete
 * read-modify-write cycle per file. This matters now that canvas autosave
 * and node/task mutations can target the same map at the same time.
 *
 * Schema versioning (SPEC §2.2):
 *   - `version: 1` — pre-Topic-Space format. Read tolerantly, no rewrite.
 *   - `version: 2` — current. Adds `spaceId` and per-node `kind` / `tag`
 *     / `taskId`. Any PUT auto-bumps to v2. New creates write v2.
 */
import { promises as fs } from 'fs';
import path from 'path';
import { ulid } from 'ulid';
import { loadConfig } from './config.js';
import type { MindMap, MindMapInput, MindMapNode, MindMapEdge, MindMapNodeKind } from '../types/mindmap.js';
import { DEFAULT_MINDMAP_NODE_KIND } from '../types/mindmap.js';

/** Current schema version for new writes. Reads accept both 1 and 2. */
const SCHEMA_VERSION = 2 as const;

/** Maps older than this are still readable. */
const MIN_SUPPORTED_VERSION = 1 as const;

async function withDir<T>(fn: (dir: string) => Promise<T>): Promise<T> {
  const config = await loadConfig();
  const dir = path.join(config.workspaceRoot, '.dailyflow', 'mindmaps');
  await fs.mkdir(dir, { recursive: true });
  return fn(dir);
}

function fileFor(dir: string, id: string): string {
  // id is generated by `ulid()` and is url-safe; no sanitisation needed.
  return path.join(dir, `${id}.json`);
}

const mutationQueue = new Map<string, Promise<void>>();

async function withFileLock<T>(filePath: string, operation: () => Promise<T>): Promise<T> {
  const previous = mutationQueue.get(filePath) ?? Promise.resolve();
  const current = previous.catch(() => undefined).then(operation);
  const settled = current.then(() => undefined, () => undefined);
  mutationQueue.set(filePath, settled);
  try {
    return await current;
  } finally {
    if (mutationQueue.get(filePath) === settled) mutationQueue.delete(filePath);
  }
}

async function readMapFile(filePath: string): Promise<MindMap> {
  const raw = await fs.readFile(filePath, 'utf-8');
  return JSON.parse(raw) as MindMap;
}

async function writeMapFile(filePath: string, map: MindMap): Promise<void> {
  await fs.writeFile(filePath, JSON.stringify(map, null, 2), 'utf-8');
}

/**
 * Fill default `kind` for any node that doesn't have one (SPEC §2.2:
 * "缺省 `kind === 'branch'` (兼容老节点)"). This is a pure function so
 * tests can pin its behavior.
 */
export function defaultNodeKind(node: MindMapNode): MindMapNode {
  if (node.kind) return node;
  return { ...node, kind: DEFAULT_MINDMAP_NODE_KIND };
}

/** Apply `defaultNodeKind` to every node in an array. */
function defaultNodeKinds(nodes: MindMapNode[]): MindMapNode[] {
  return nodes.map(defaultNodeKind);
}

function emptyMap(title: string, now: string, spaceId?: string): MindMap {
  const id = ulid();
  const rootId = ulid();
  const root: MindMapNode = {
    id: rootId,
    text: title || '中心主题',
    position: { x: 0, y: 0 },
    kind: 'root',
  };
  return {
    id,
    title: title || '未命名导图',
    rootId,
    nodes: [root],
    edges: [],
    version: SCHEMA_VERSION,
    ...(spaceId ? { spaceId } : {}),
    createdAt: now,
    updatedAt: now,
  };
}

export async function listMindMaps(): Promise<MindMap[]> {
  return withDir(async (dir) => {
    const entries = await fs.readdir(dir);
    const maps: MindMap[] = [];
    for (const entry of entries) {
      if (!entry.endsWith('.json')) continue;
      const filePath = path.join(dir, entry);
      try {
        const map = await withFileLock(filePath, () => readMapFile(filePath));
        // Accept any supported version; unknown future versions are skipped
        // so a forward-incompatible change doesn't break the whole list.
        if (map && map.version >= MIN_SUPPORTED_VERSION && map.version <= SCHEMA_VERSION) {
          maps.push(map);
        }
      } catch (err) {
        // A corrupt file should not break the whole list. Log and skip.
        console.error(`[mindmaps] skip unreadable ${entry}:`, err);
      }
    }
    // Newest first by updatedAt.
    maps.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
    return maps;
  });
}

export async function getMindMap(id: string): Promise<MindMap | null> {
  return withDir(async (dir) => {
    const filePath = fileFor(dir, id);
    return withFileLock(filePath, async () => {
      try {
        return await readMapFile(filePath);
      } catch (err: any) {
        if (err && err.code === 'ENOENT') return null;
        throw err;
      }
    });
  });
}

export async function createMindMap(input: Partial<MindMapInput> = {}): Promise<MindMap> {
  const now = new Date().toISOString();
  const title = (input.title ?? '').trim() || '未命名导图';
  const map = emptyMap(title, now, input.spaceId);
  if (input.rootId) map.rootId = input.rootId;
  if (Array.isArray(input.nodes) && input.nodes.length > 0) {
    map.nodes = defaultNodeKinds(input.nodes);
    if (!map.nodes.find((n) => n.id === map.rootId) && map.nodes[0]) {
      map.rootId = map.nodes[0].id;
    }
  }
  if (Array.isArray(input.edges)) map.edges = input.edges;
  return withDir(async (dir) => {
    const filePath = fileFor(dir, map.id);
    return withFileLock(filePath, async () => {
      await writeMapFile(filePath, map);
      return map;
    });
  });
}

export interface MindMapUpdate {
  title?: string;
  rootId?: string;
  nodes?: MindMapNode[];
  edges?: MindMapEdge[];
  /**
   * v2: allow the route (or TopicSpace) to set the reverse link. If
   * omitted, the existing `spaceId` is preserved.
   */
  spaceId?: string | null;
}

export async function updateMindMap(id: string, patch: MindMapUpdate): Promise<MindMap | null> {
  const now = new Date().toISOString();
  return withDir(async (dir) => {
    const filePath = fileFor(dir, id);
    return withFileLock(filePath, async () => {
      let existing: MindMap;
      try {
        existing = await readMapFile(filePath);
      } catch (err: any) {
        if (err && err.code === 'ENOENT') return null;
        throw err;
      }
      // Any PUT auto-bumps to the current schema version (SPEC §3.3).
      const baseNodes = patch.nodes !== undefined ? patch.nodes : existing.nodes;
      const next: MindMap = {
        ...existing,
        title: patch.title !== undefined ? patch.title : existing.title,
        rootId: patch.rootId !== undefined ? patch.rootId : existing.rootId,
        nodes: defaultNodeKinds(baseNodes),
        edges: patch.edges !== undefined ? patch.edges : existing.edges,
        version: SCHEMA_VERSION,
        updatedAt: now,
      };
      if (patch.spaceId !== undefined) {
        if (patch.spaceId === null) delete next.spaceId;
        else next.spaceId = patch.spaceId;
      } else if (existing.spaceId) {
        next.spaceId = existing.spaceId;
      }
      await writeMapFile(filePath, next);
      return next;
    });
  });
}

export async function deleteMindMap(id: string): Promise<boolean> {
  return withDir(async (dir) => {
    const filePath = fileFor(dir, id);
    return withFileLock(filePath, async () => {
      try {
        await fs.unlink(filePath);
        return true;
      } catch (err: any) {
        if (err && err.code === 'ENOENT') return false;
        throw err;
      }
    });
  });
}

/**
 * Update a single node in a mindmap without round-tripping the full
 * `nodes` array. Returns the updated MindMap (with version bump, kind
 * defaulting, and updatedAt). Returns `null` if the map or node does
 * not exist.
 *
 * The patch is shallow: it overwrites the named keys on the matching
 * node. To delete an optional field, set it to `undefined` in the
 * patch; the implementation strips the key from the stored object so
 * the file on disk reflects the cleared state.
 *
 * Rationale: the route handlers (promote-to-task, link-task, repair)
 * only need to flip one node's kind/taskId. The existing `updateMindMap`
 * would force the caller to send back the entire `nodes` array, which
 * is both wasteful and a footgun (any node dropped on the way would
 * be silently deleted from the file).
 */
export async function updateNodeInMindMap(
  mindmapId: string,
  nodeId: string,
  patch: Partial<MindMapNode>,
): Promise<MindMap | null> {
  const now = new Date().toISOString();
  return withDir(async (dir) => {
    const filePath = fileFor(dir, mindmapId);
    return withFileLock(filePath, async () => {
      let existing: MindMap;
      try {
        existing = await readMapFile(filePath);
      } catch (err: any) {
        if (err && err.code === 'ENOENT') return null;
        throw err;
      }
      const idx = existing.nodes.findIndex(n => n.id === nodeId);
      if (idx === -1) return null;
      const merged: MindMapNode = { ...existing.nodes[idx] };
      for (const [k, v] of Object.entries(patch)) {
        if (v === undefined) delete (merged as any)[k];
        else (merged as any)[k] = v;
      }
      if (!merged.kind) merged.kind = DEFAULT_MINDMAP_NODE_KIND;
      const nextNodes = existing.nodes.slice();
      nextNodes[idx] = merged;
      const next: MindMap = {
        ...existing,
        nodes: nextNodes,
        version: SCHEMA_VERSION,
        updatedAt: now,
      };
      await writeMapFile(filePath, next);
      return next;
    });
  });
}

/**
 * Walk the parent chain of a node and collect `kind: 'tag'` labels in
 * root-to-leaf order. Used by `appendTaskToMarkdown` (Topic Spaces
 * Phase 3) to inherit tag labels from the source mindmap.
 *
 * Returns an empty array if the mindmap or node does not exist, or if
 * no ancestor is a tag node. Multiple tag ancestors are deduplicated
 * (case-insensitive) while preserving first-occurrence order.
 *
 * Edges are interpreted as parent → child (`source` is the parent).
 * This matches the convention used everywhere else in the codebase
 * (see `MindMapEdge` in `types/mindmap.ts`).
 */
export function getInheritedTagsFromMap(
  map: MindMap,
  nodeId: string,
): string[] {
  // Build a parent map once: child -> parent (first occurrence wins;
  // a multi-parent cycle is treated as a no-parent for that child).
  const parentOf = new Map<string, string>();
  for (const edge of map.edges) {
    if (!parentOf.has(edge.target)) parentOf.set(edge.target, edge.source);
  }

  // Walk from node up to the root, collecting tag nodes. The root is
  // the node with `kind: 'root'` (or the node the mindmap declares as
  // `rootId` if no node carries the discriminator).
  //
  // We collect in leaf-to-root order, then reverse at the end so the
  // returned list reads root-to-leaf. That's the order that maps onto
  // a natural "broader → narrower" tag hierarchy when the markdown
  // line is rendered, and it also matches the order the spec example
  // (SPEC §2) shows for a single inheritance path.
  const rootId = map.rootId;
  const seen = new Set<string>();
  const out: string[] = [];
  let cur: string | undefined = nodeId;
  // Cycle guard: cap the walk at nodes.length so a malformed graph
  // can't spin forever.
  let safety = map.nodes.length + 1;
  while (cur && safety-- > 0) {
    if (cur === rootId) break; // reached the root; stop without including it
    const node = map.nodes.find(n => n.id === cur);
    if (!node) break;
    if (node.kind === 'tag' && node.tag) {
      const key = node.tag.toLowerCase();
      if (!seen.has(key)) {
        seen.add(key);
        out.push(node.tag);
      }
    }
    cur = parentOf.get(cur);
  }
  out.reverse();
  return out;
}

/**
 * Re-export the kind constant for callers that don't want a second import.
 */
export type { MindMapNodeKind };
